@host = http://localhost:8000

###
#login 
GET  {{host}}/index.php/loginn
Content-Type: application/json

{
"nome_alternativo":"MARLON",
"password":"123456",
"acessa_sistema":"S",
"ativo": "S",
"empresa_id": 1
}


###
//logout
GET  {{host}}/index.php/login

###